
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act5_analisis_sintactico;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser5 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser5() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser5(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser5(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\047\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\002\004\000\002\002\003\000\002\003\005" +
    "\000\002\004\003\000\002\004\004\000\002\005\005\000" +
    "\002\006\003\000\002\006\005\000\002\007\006\000\002" +
    "\007\007\000\002\010\004\000\002\010\003\000\002\011" +
    "\003\000\002\011\003\000\002\011\004\000\002\012\006" +
    "\000\002\013\010\000\002\013\006\000\002\020\004\000" +
    "\002\020\002\000\002\014\003\000\002\014\003\000\002" +
    "\014\003\000\002\014\003\000\002\014\003\000\002\014" +
    "\003\000\002\014\003\000\002\015\003\000\002\015\005" +
    "\000\002\016\003\000\002\017\003\000\002\017\003\000" +
    "\002\017\003\000\002\017\003\000\002\017\003\000\002" +
    "\017\003" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\010\004\005\005\007\006\013\001\002\000" +
    "\004\002\101\001\002\000\004\026\073\001\002\000\004" +
    "\002\ufffd\001\002\000\004\026\073\001\002\000\006\005" +
    "\007\006\ufffb\001\002\000\004\006\013\001\002\000\006" +
    "\005\007\006\013\001\002\000\004\026\014\001\002\000" +
    "\004\022\015\001\002\000\026\003\025\007\030\010\016" +
    "\011\034\012\024\013\035\014\020\015\022\023\021\026" +
    "\031\001\002\000\004\026\uffea\001\002\000\026\003\ufff2" +
    "\007\ufff2\010\ufff2\011\ufff2\012\ufff2\013\ufff2\014\ufff2\015" +
    "\ufff2\023\ufff2\026\ufff2\001\002\000\004\026\uffe6\001\002" +
    "\000\004\002\ufff6\001\002\000\004\026\uffe5\001\002\000" +
    "\026\003\ufff1\007\ufff1\010\ufff1\011\ufff1\012\ufff1\013\ufff1" +
    "\014\ufff1\015\ufff1\023\ufff1\026\ufff1\001\002\000\004\026" +
    "\uffe8\001\002\000\004\020\064\001\002\000\004\026\031" +
    "\001\002\000\004\023\053\001\002\000\020\010\016\011" +
    "\034\012\024\013\035\014\020\015\022\026\031\001\002" +
    "\000\012\020\uffe1\024\uffe1\025\uffe1\026\uffe1\001\002\000" +
    "\004\026\uffe4\001\002\000\026\003\025\007\030\010\016" +
    "\011\034\012\024\013\035\014\020\015\022\023\ufff3\026" +
    "\031\001\002\000\004\026\uffe9\001\002\000\004\026\uffe7" +
    "\001\002\000\004\023\ufff4\001\002\000\004\026\031\001" +
    "\002\000\006\020\042\025\041\001\002\000\016\016\047" +
    "\017\045\027\043\030\050\031\051\032\046\001\002\000" +
    "\026\003\uffed\007\uffed\010\uffed\011\uffed\012\uffed\013\uffed" +
    "\014\uffed\015\uffed\023\uffed\026\uffed\001\002\000\004\020" +
    "\uffe0\001\002\000\004\020\052\001\002\000\004\020\uffdb" +
    "\001\002\000\004\020\uffdd\001\002\000\004\020\uffdc\001" +
    "\002\000\004\020\uffdf\001\002\000\004\020\uffde\001\002" +
    "\000\026\003\uffee\007\uffee\010\uffee\011\uffee\012\uffee\013" +
    "\uffee\014\uffee\015\uffee\023\uffee\026\uffee\001\002\000\004" +
    "\002\ufff5\001\002\000\010\020\uffeb\024\056\025\057\001" +
    "\002\000\010\020\uffe3\024\uffe3\025\uffe3\001\002\000\004" +
    "\026\031\001\002\000\016\016\047\017\045\027\043\030" +
    "\050\031\051\032\046\001\002\000\004\020\061\001\002" +
    "\000\026\003\uffef\007\uffef\010\uffef\011\uffef\012\uffef\013" +
    "\uffef\014\uffef\015\uffef\023\uffef\026\uffef\001\002\000\004" +
    "\020\uffec\001\002\000\010\020\uffe2\024\uffe2\025\uffe2\001" +
    "\002\000\026\003\ufff0\007\ufff0\010\ufff0\011\ufff0\012\ufff0" +
    "\013\ufff0\014\ufff0\015\ufff0\023\ufff0\026\ufff0\001\002\000" +
    "\004\002\uffff\001\002\000\004\006\013\001\002\000\004" +
    "\002\000\001\002\000\004\002\ufffe\001\002\000\004\006" +
    "\ufffa\001\002\000\006\020\075\021\074\001\002\000\006" +
    "\020\ufff8\021\ufff8\001\002\000\004\026\076\001\002\000" +
    "\006\005\ufff9\006\ufff9\001\002\000\006\020\ufff7\021\ufff7" +
    "\001\002\000\006\020\100\021\074\001\002\000\006\005" +
    "\ufffc\006\ufffc\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\077\000\014\002\003\003\011\004\010\005\007\007" +
    "\005\001\001\000\002\001\001\000\004\006\076\001\001" +
    "\000\002\001\001\000\004\006\071\001\001\000\006\004" +
    "\070\005\007\001\001\000\004\007\067\001\001\000\010" +
    "\004\065\005\007\007\064\001\001\000\002\001\001\000" +
    "\002\001\001\000\016\010\026\011\032\012\016\013\022" +
    "\014\025\016\031\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\015\053\016\054\001\001\000\002\001\001\000\006" +
    "\014\036\016\031\001\001\000\002\001\001\000\002\001" +
    "\001\000\016\010\035\011\032\012\016\013\022\014\025" +
    "\016\031\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\016\037\001\001\000\002\001\001" +
    "\000\004\017\043\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\020\057\001\001" +
    "\000\002\001\001\000\004\016\062\001\001\000\004\017" +
    "\061\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\007\066\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser5$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser5$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser5$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public void report_error(String message, Object info) {
        String tokenStr = "desconocido";
        int linea = 0;
        int columna = 0;

        if (info instanceof Symbol) {
            Symbol s = (Symbol) info;
            linea = s.left;
            columna = s.right;
            tokenStr = (s.value != null) ? s.value.toString() : "EOF";
        }

        System.out.println("Error sintactico en linea " + linea + ", columna " + columna + ":");
        System.out.println("se encontro '" + tokenStr + "'");
        System.out.println("Descripcion: " + message);
    }

    public void report_fatal_error(String message, Object info) throws Exception {
        report_error(message, info);
        throw new Exception("Error fatal en el analisis sintactico.");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser5$actions {
  private final Parser5 parser;

  /** Constructor */
  CUP$Parser5$actions(Parser5 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser5$do_action_part00000000(
    int                        CUP$Parser5$act_num,
    java_cup.runtime.lr_parser CUP$Parser5$parser,
    java.util.Stack            CUP$Parser5$stack,
    int                        CUP$Parser5$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser5$result;

      /* select the action based on the action number */
      switch (CUP$Parser5$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= archivo EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)).value;
		RESULT = start_val;
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser5$parser.done_parsing();
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // archivo ::= paquete importaciones clase_principal 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("archivo",0, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // archivo ::= paquete clase_principal 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("archivo",0, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // archivo ::= importaciones clase_principal 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("archivo",0, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // archivo ::= clase_principal 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("archivo",0, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // paquete ::= PAQUETE ubicacion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("paquete",1, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // importaciones ::= importacion 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("importaciones",2, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // importaciones ::= importacion importaciones 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("importaciones",2, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // importacion ::= IMPORTAR ubicacion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("importacion",3, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // ubicacion ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("ubicacion",4, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // ubicacion ::= ubicacion PUNTO IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("ubicacion",4, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // clase_principal ::= CLASE IDENTIFICADOR LLAVE_A LLAVE_C 
            {
              Object RESULT =null;
		 System.out.println("Clase vacia reconocida."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("clase_principal",5, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-3)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // clase_principal ::= CLASE IDENTIFICADOR LLAVE_A cuerpo_clase LLAVE_C 
            {
              Object RESULT =null;
		 System.out.println("Clase con miembros reconocida."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("clase_principal",5, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-4)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // cuerpo_clase ::= miembro cuerpo_clase 
            {
              Object RESULT =null;
		 System.out.println("Miembro de clase reconocido."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("cuerpo_clase",6, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // cuerpo_clase ::= miembro 
            {
              Object RESULT =null;
		 System.out.println("Miembro de clase reconocido."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("cuerpo_clase",6, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // miembro ::= atributo 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("miembro",7, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // miembro ::= constante 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("miembro",7, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // miembro ::= error PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Declaracion invalida recuperada; se continua con el siguiente miembro."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("miembro",7, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // atributo ::= tipo lista_identificadores opt_inicializacion PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Atributo o variable reconocido."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("atributo",8, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-3)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // constante ::= FINAL tipo identificador IGUAL valor PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Constante reconocida."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("constante",9, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-5)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // constante ::= FINAL tipo identificador PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Error: la constante debe inicializarse."); 
              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("constante",9, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-3)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // opt_inicializacion ::= IGUAL valor 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("opt_inicializacion",14, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-1)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // opt_inicializacion ::= 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("opt_inicializacion",14, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // tipo ::= INT 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("tipo",10, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipo ::= FLOAT 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("tipo",10, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // tipo ::= DOUBLE 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("tipo",10, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // tipo ::= CHAR 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("tipo",10, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // tipo ::= BOOLEAN 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("tipo",10, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // tipo ::= STRING 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("tipo",10, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // tipo ::= identificador 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("tipo",10, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // lista_identificadores ::= identificador 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("lista_identificadores",11, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // lista_identificadores ::= lista_identificadores COMA identificador 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("lista_identificadores",11, ((java_cup.runtime.Symbol)CUP$Parser5$stack.elementAt(CUP$Parser5$top-2)), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // identificador ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("identificador",12, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // valor ::= NUMERO 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("valor",13, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // valor ::= DECIMAL 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("valor",13, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // valor ::= CADENA 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("valor",13, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // valor ::= CARACTER 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("valor",13, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // valor ::= VERDADERO 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("valor",13, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // valor ::= FALSO 
            {
              Object RESULT =null;

              CUP$Parser5$result = parser.getSymbolFactory().newSymbol("valor",13, ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser5$stack.peek()), RESULT);
            }
          return CUP$Parser5$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser5$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser5$do_action(
    int                        CUP$Parser5$act_num,
    java_cup.runtime.lr_parser CUP$Parser5$parser,
    java.util.Stack            CUP$Parser5$stack,
    int                        CUP$Parser5$top)
    throws java.lang.Exception
    {
              return CUP$Parser5$do_action_part00000000(
                               CUP$Parser5$act_num,
                               CUP$Parser5$parser,
                               CUP$Parser5$stack,
                               CUP$Parser5$top);
    }
}

}
