
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act4_analisis_gestion_errores;

import java_cup.runtime.*;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class Parser4 extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return sym.class;
}

  /** Default constructor. */
  @Deprecated
  public Parser4() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public Parser4(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Parser4(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\021\000\002\002\004\000\002\002\005\000\002\002" +
    "\004\000\002\002\004\000\002\003\005\000\002\003\005" +
    "\000\002\003\005\000\002\004\004\000\002\004\002\000" +
    "\002\005\005\000\002\005\005\000\002\005\005\000\002" +
    "\007\005\000\002\007\003\000\002\006\006\000\002\006" +
    "\006\000\002\006\005" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\042\000\012\003\004\004\006\005\ufff9\006\ufff9\001" +
    "\002\000\004\006\014\001\002\000\004\002\043\001\002" +
    "\000\006\003\037\013\026\001\002\000\006\005\ufff9\006" +
    "\ufff9\001\002\000\006\005\011\006\014\001\002\000\006" +
    "\003\025\013\026\001\002\000\004\002\uffff\001\002\000" +
    "\006\005\ufffa\006\ufffa\001\002\000\006\003\015\013\016" +
    "\001\002\000\004\011\022\001\002\000\006\003\017\011" +
    "\020\001\002\000\004\002\ufff1\001\002\000\004\012\021" +
    "\001\002\000\004\002\ufff3\001\002\000\004\012\023\001" +
    "\002\000\004\002\ufff2\001\002\000\010\003\031\007\032" +
    "\010\030\001\002\000\004\007\027\001\002\000\010\003" +
    "\ufff4\007\ufff4\010\ufff4\001\002\000\006\005\ufff7\006\ufff7" +
    "\001\002\000\004\013\033\001\002\000\006\005\ufff6\006" +
    "\ufff6\001\002\000\006\005\ufff8\006\ufff8\001\002\000\010" +
    "\003\ufff5\007\ufff5\010\ufff5\001\002\000\006\005\011\006" +
    "\014\001\002\000\004\002\000\001\002\000\010\003\041" +
    "\007\042\010\030\001\002\000\004\007\040\001\002\000" +
    "\006\005\ufffc\006\ufffc\001\002\000\006\005\ufffb\006\ufffb" +
    "\001\002\000\006\005\ufffd\006\ufffd\001\002\000\004\002" +
    "\001\001\002\000\004\002\ufffe\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\042\000\010\002\004\003\006\004\007\001\001\000" +
    "\004\006\043\001\001\000\002\001\001\000\004\007\035" +
    "\001\001\000\004\004\033\001\001\000\006\005\012\006" +
    "\011\001\001\000\004\007\023\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\005\012\006\034\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Parser4$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Parser4$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Parser4$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    // 3.1 Error recuperable
    public void report_error(String message, Object info) {
        if (info instanceof Symbol) {
            Symbol s = (Symbol) info;
            String tokenStr = (s.value != null) ? s.value.toString() : (s.sym == sym.EOF ? "EOF" : "desconocido");
            System.out.println("Error sintáctico en linea " + s.left + ", columna " + s.right + ": se encontró '" + tokenStr + "'");
        } else {
            System.out.println("Error sintáctico: " + message);
        }
    }

    // 3.2 Error fatal 
    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
        if (info instanceof Symbol) {
            Symbol s = (Symbol) info;
            String tokenStr = (s.value != null) ? s.value.toString() : (s.sym == sym.EOF ? "EOF" : "desconocido");
            System.out.println("Error fatal en linea " + s.left + ", columna " + s.right + ": se encontró '" + tokenStr + "'");
        } else {
            System.out.println("Error fatal: " + message);
        }
        throw new Exception("Análisis interrumpido por error fatal.");
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$Parser4$actions {
  private final Parser4 parser;

  /** Constructor */
  CUP$Parser4$actions(Parser4 parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$Parser4$do_action_part00000000(
    int                        CUP$Parser4$act_num,
    java_cup.runtime.lr_parser CUP$Parser4$parser,
    java.util.Stack            CUP$Parser4$stack,
    int                        CUP$Parser4$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Parser4$result;

      /* select the action based on the action number */
      switch (CUP$Parser4$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= archivo EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Parser4$stack.elementAt(CUP$Parser4$top-1)).value;
		RESULT = start_val;
              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-1)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Parser4$parser.done_parsing();
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // archivo ::= paquete importaciones clase_principal 
            {
              Object RESULT =null;

              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("archivo",0, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-2)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // archivo ::= importaciones clase_principal 
            {
              Object RESULT =null;

              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("archivo",0, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-1)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // archivo ::= error clase_principal 
            {
              Object RESULT =null;
		 System.out.println("Recuperacion de error en la cabecera del archivo."); 
              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("archivo",0, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-1)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // paquete ::= PAQUETE ubicacion PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Paquete reconocido correctamente"); 
              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("paquete",1, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-2)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // paquete ::= PAQUETE error PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Error recuperable en la ruta del paquete"); 
              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("paquete",1, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-2)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // paquete ::= PAQUETE ubicacion error 
            {
              Object RESULT =null;
		 System.out.println("Error recuperable: falta punto y coma en el paquete"); 
              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("paquete",1, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-2)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // importaciones ::= importaciones importacion 
            {
              Object RESULT =null;

              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("importaciones",2, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-1)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // importaciones ::= 
            {
              Object RESULT =null;

              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("importaciones",2, ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // importacion ::= IMPORTAR ubicacion PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Importacion reconocida correctamente"); 
              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("importacion",3, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-2)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // importacion ::= IMPORTAR error PUNTO_COMA 
            {
              Object RESULT =null;
		 System.out.println("Error recuperable en la ruta de importacion"); 
              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("importacion",3, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-2)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // importacion ::= IMPORTAR ubicacion error 
            {
              Object RESULT =null;
		 System.out.println("Error recuperable: falta punto y coma en la importacion"); 
              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("importacion",3, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-2)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // ubicacion ::= ubicacion PUNTO IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("ubicacion",5, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-2)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // ubicacion ::= IDENTIFICADOR 
            {
              Object RESULT =null;

              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("ubicacion",5, ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // clase_principal ::= CLASE IDENTIFICADOR LLAVE_A LLAVE_C 
            {
              Object RESULT =null;
		 
        System.out.println("Clase principal reconocida correctamente");
        System.out.println("Estructura de llaves válida");        
    
              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("clase_principal",4, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-3)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // clase_principal ::= CLASE error LLAVE_A LLAVE_C 
            {
              Object RESULT =null;
		 System.out.println("Error recuperable: nombre de clase inválido o faltante"); 
              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("clase_principal",4, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-3)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // clase_principal ::= CLASE IDENTIFICADOR error 
            {
              Object RESULT =null;
		 System.out.println("Error recuperable: llaves incorrectas o faltantes en la clase"); 
              CUP$Parser4$result = parser.getSymbolFactory().newSymbol("clase_principal",4, ((java_cup.runtime.Symbol)CUP$Parser4$stack.elementAt(CUP$Parser4$top-2)), ((java_cup.runtime.Symbol)CUP$Parser4$stack.peek()), RESULT);
            }
          return CUP$Parser4$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$Parser4$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$Parser4$do_action(
    int                        CUP$Parser4$act_num,
    java_cup.runtime.lr_parser CUP$Parser4$parser,
    java.util.Stack            CUP$Parser4$stack,
    int                        CUP$Parser4$top)
    throws java.lang.Exception
    {
              return CUP$Parser4$do_action_part00000000(
                               CUP$Parser4$act_num,
                               CUP$Parser4$parser,
                               CUP$Parser4$stack,
                               CUP$Parser4$top);
    }
}

}
