
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act4_analisis_gestion_errores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int IMPORTAR = 3;
  public static final int PUNTO = 6;
  public static final int PUNTO_COMA = 5;
  public static final int LLAVE_C = 8;
  public static final int EOF = 0;
  public static final int LLAVE_A = 7;
  public static final int CLASE = 4;
  public static final int error = 1;
  public static final int PAQUETE = 2;
  public static final int IDENTIFICADOR = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAQUETE",
  "IMPORTAR",
  "CLASE",
  "PUNTO_COMA",
  "PUNTO",
  "LLAVE_A",
  "LLAVE_C",
  "IDENTIFICADOR"
  };
}

