
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package act5_analisis_sintactico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PUNTO = 15;
  public static final int CADENA = 23;
  public static final int IGUAL = 19;
  public static final int INT = 6;
  public static final int DECIMAL = 22;
  public static final int CHAR = 9;
  public static final int ERROR_LEXICO = 25;
  public static final int VERDADERO = 12;
  public static final int CLASE = 4;
  public static final int CARACTER = 24;
  public static final int BOOLEAN = 10;
  public static final int FALSO = 13;
  public static final int COMA = 18;
  public static final int STRING = 11;
  public static final int FLOAT = 7;
  public static final int PAQUETE = 2;
  public static final int EOF = 0;
  public static final int NUMERO = 21;
  public static final int FINAL = 5;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 20;
  public static final int LLAVE_C = 17;
  public static final int LLAVE_A = 16;
  public static final int PUNTO_COMA = 14;
  public static final int IMPORTAR = 3;
  public static final int DOUBLE = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PAQUETE",
  "IMPORTAR",
  "CLASE",
  "FINAL",
  "INT",
  "FLOAT",
  "DOUBLE",
  "CHAR",
  "BOOLEAN",
  "STRING",
  "VERDADERO",
  "FALSO",
  "PUNTO_COMA",
  "PUNTO",
  "LLAVE_A",
  "LLAVE_C",
  "COMA",
  "IGUAL",
  "IDENTIFICADOR",
  "NUMERO",
  "DECIMAL",
  "CADENA",
  "CARACTER",
  "ERROR_LEXICO"
  };
}

